apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-processor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: text-processor
  template:
    metadata:
      labels:
        app: text-processor
    spec:
      containers:
        - name: text-processor
          image: my-text-processor
          resources:
            limits:
              memory: "200Mi"
              cpu: "500m"
